// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rdvckuqtcqgwgyeowllq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkdmNrdXF0Y3Fnd2d5ZW93bGxxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NTk0MTIsImV4cCI6MjA3MTQzNTQxMn0.GPmWL1keCfTsUdA97eH7ZIit8QUttqGIZ08ryeTboic";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});